# Generated by Django 4.0.2 on 2022-02-27 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0002_section_section_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('type',
                 models.CharField(
                     choices=[
                         ('ReviewUpvoted',
                          'When my review is upvoted'),
                         ('Notice',
                          'Announcements from theCourseForum staff'),
                         ('NewReview',
                          'When a new review is posted for the course I follow')],
                     max_length=50)),
                ('content',
                 models.TextField()),
                ('is_read',
                 models.BooleanField(
                     default=False)),
                ('created',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('mime_type',
                 models.CharField(
                     choices=[
                         ('text/plain',
                          'Plain'),
                         ('text/html',
                          'Html')],
                     default='text/plain',
                     max_length=50)),
                ('title',
                 models.CharField(
                     blank=True,
                     default='',
                     max_length=255)),
                ('next_path',
                 models.CharField(
                     max_length=255)),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=[
                    'is_read',
                    'created'],
                name='tcf_website_is_read_ae2ff3_idx'),
        ),
    ]
